OBJS = agi.obj agi_v2.obj agi_v3.obj checks.obj cli.obj console.obj cycle.obj \
	font.obj getopt.obj getopt1.obj global.obj graphics.obj id.obj \
	inv.obj keyboard.obj logic.obj lzw.obj main.obj menu.obj motion.obj objects.obj \
	op_cmd.obj op_dbg.obj op_test.obj patches.obj picture.obj picview.obj \
	rand.obj savegame.obj silent.obj sound.obj sprite.obj text.obj view.obj words.obj \
	daudio.obj fileglob.obj path.obj 

CC = wcl386 
MEM = /3s
ZOPT = 
OPT = /Ox
CPU = 
OS = 
DEBUG = # /Zi
INCLUDES =  -Iinclude

CFLAGS =  $(MEM) $(CPU) $(OPT)  $(OS) $(DEBUG) -D__MSDOS__  $(INCLUDES)
ZCFLAGS = $(MEM) $(CPU) $(ZOPT) $(OS) $(DEBUG) -D__MSDOS__  $(INCLUDES)

386.exe: $(OBJS) pharcga3.obj
	386linkr.exe @386
	copy /Y 386.exe \dos\sq2
	dosbox

pharcga3.obj: pharcga3.c
	@echo this needs to be built with Watcom 10
	@echo
	@echo $(CC) $(CFLAGS) -c pharcga3.c
	uudecode pharcga3.txt

daudio.obj: dummy.c
	$(CC) $(CFLAGS) /c /Fodaudio.obj dummy.c


